# Rust Daily RSS 源配置文件
# 
# 格式: name = "RSS源名称", url = "RSS链接地址"
# 支持的源类型：RSS 2.0, Atom 1.0
# 
# 配置说明：
# - name: RSS 源的显示名称，会在日报中显示
# - url: RSS feed 的完整 URL 地址
# - 新增源后重新运行程序即可生效
# - 建议添加与 Rust 技术相关的高质量源

[[rss_sources]]
name = "Rust Blog"
url = "https://blog.rust-lang.org/feed.xml"

[[rss_sources]]
name = "This Week in Rust"
url = "https://this-week-in-rust.org/rss.xml"

[[rss_sources]]
name = "Rust Users Forum"
url = "https://users.rust-lang.org/latest.rss"

[[rss_sources]]
name = "Rust Internals"
url = "https://internals.rust-lang.org/latest.rss"

[[rss_sources]]
name = "Jorge Aparicio's Blog"
url = "https://blog.japaric.io/index.xml"

[[rss_sources]]
name = "Rust中文社区"
url = "https://rustcc.cn/rss"
